I:
cd GeneratingPDF
node generate-pdf.js ewogICJtb2RlbE51bWJlciI6ICIxMzEwRkIiLAogICJzcGVjaWZpY2F0aW9uIjogewogICAgIm9wdGlvbnMiOiBbICJVcGhvbHN0ZXJ5IFNlbGVjdGlvbiIsICJGdWxsIGJsYWNrIGNoYWlyIiwgIlVwaG9sc3RlcnkgU2VsZWN0b24iIF0sCiAgICAicHJpY2VzIjogIFswLCAyMzcsIDBdCiAgfQp9
pause 